<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test</name>
   <tag></tag>
   <elementGuidId>2c5b720d-d9b7-4d8b-b0e5-73b56252db92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description2d729599-3453-48a7-b93f-845cf7b75dfd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='description2d729599-3453-48a7-b93f-845cf7b75dfd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;test&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b8dd1abe-e2a9-4719-9d10-21daffaad499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>7e5a9ce5-a30f-4304-96e9-a7d1ff7ed80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-collapse collapse show</value>
      <webElementGuid>a245505e-69a1-40c3-9f97-47a576cee2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description2d729599-3453-48a7-b93f-845cf7b75dfd</value>
      <webElementGuid>17f985af-9fdf-4362-9577-63e2612d68d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>61bd0c13-cc7e-40db-bead-9b343487fc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flush-collapse0f01b287-5e2e-4996-8824-f063ac57e2c2&quot;)/div[@class=&quot;ec-row d-flex flex-row card-course py-2&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;d-flex flex-row gap-2 checkbox-container&quot;]/div[@class=&quot;d-flex flex-column&quot;]/span[@id=&quot;description2d729599-3453-48a7-b93f-845cf7b75dfd&quot;]</value>
      <webElementGuid>9e7b4c52-76f9-43c9-91ba-6104ee3619af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='description2d729599-3453-48a7-b93f-845cf7b75dfd']</value>
      <webElementGuid>c10ad410-15eb-413d-9529-b6a653a0bc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flush-collapse0f01b287-5e2e-4996-8824-f063ac57e2c2']/div[5]/div/div/div/span[2]</value>
      <webElementGuid>7f96a8ec-8f0d-4340-8cf3-cd85cfa943db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Golang Database'])[1]/following::span[1]</value>
      <webElementGuid>946459d6-fe13-4581-92e3-e0306e3b7bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check / uncheck module according your need'])[1]/following::span[2]</value>
      <webElementGuid>14bea05f-bc5e-4bb1-a43a-daf84d55a1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp200,000'])[1]/preceding::span[1]</value>
      <webElementGuid>44143ba4-e0a6-48d7-80c0-ae67e61133d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='swift'])[1]/preceding::span[2]</value>
      <webElementGuid>61f06d24-1b4c-4a97-a87f-612a74df0c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>0a1d525c-edf2-4172-ac17-2e433964b53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>5b36afd1-070e-404b-8672-9f36ae35f9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'description2d729599-3453-48a7-b93f-845cf7b75dfd' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>2af41ad0-b0d7-4f8c-b05f-58835c4ff95e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
