<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rp200,000_1</name>
   <tag></tag>
   <elementGuidId>7f23bbfa-0bd5-455a-8eca-ccaf3cc28a46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pb-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete all'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Rp200,000&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0776b963-38d0-4532-88a6-7d795d846745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-5</value>
      <webElementGuid>abac54b9-51e1-43fe-a4e2-52522b3547c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp200,000</value>
      <webElementGuid>b47c8740-c4d2-49f4-aa36-fe63ce0360bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-pages[1]/div[@class=&quot;wrapper-container&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;d-flex flex-column z-1 position-relative&quot;]/div[@class=&quot;col-11 mx-auto&quot;]/app-shopping-cart[1]/div[@class=&quot;d-flex flex-column pt-3&quot;]/div[@class=&quot;row d-flex flex-row pt-4 gap-5&quot;]/div[@class=&quot;col-7 wrapper-left px-3 py-3&quot;]/div[@class=&quot;d-flex gap-3 py-3&quot;]/div[@class=&quot;card-custom&quot;]/div[@class=&quot;ec-row&quot;]/div[@class=&quot;ec-col-6 text-end align-bottom mt-3&quot;]/div[@class=&quot;discounted-price&quot;]/span[@class=&quot;pb-5&quot;]</value>
      <webElementGuid>96ac188d-db83-48fa-9c57-cc9cc5ef003c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete all'])[1]/following::span[1]</value>
      <webElementGuid>c72d749f-3340-4ddb-8c9c-0038d1e0f578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select all products'])[1]/following::span[2]</value>
      <webElementGuid>c956ca92-b132-418e-a9a3-f756a9e3feaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bismillah bisa edited'])[1]/preceding::span[1]</value>
      <webElementGuid>cb5d8703-5ada-49b8-8d51-6fb4098cb5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize package'])[1]/preceding::span[2]</value>
      <webElementGuid>46859976-71c8-46a7-bec7-086dfea97c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rp200,000']/parent::*</value>
      <webElementGuid>df055155-cb65-4aa3-a4a2-24ab96dd42fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div/span</value>
      <webElementGuid>579c2d0b-7e41-4caf-98f8-db627194c00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rp200,000' or . = 'Rp200,000')]</value>
      <webElementGuid>243944ca-d2b5-4c26-8f29-530230cdf76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
