<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New Password_newPassword</name>
   <tag></tag>
   <elementGuidId>d1952c43-31d0-48cd-b82f-774cbe1700b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;New Password&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af3bf7e8-3818-4dd8-9d0a-ac9a7d1eb590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPassword</value>
      <webElementGuid>32fbd9e7-b7d3-4918-bba9-e23d54f52615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>766c03be-92f8-4d75-848e-35ab0e109c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New Password</value>
      <webElementGuid>0e5bf060-a354-44b0-91e5-dc314adf00c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>newPassword</value>
      <webElementGuid>b2cb0641-3dc7-4b45-98f4-7de1b75e6e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded ec-neutral-500 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>47b70657-fe3b-4125-8510-92fe328b555d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPassword&quot;)</value>
      <webElementGuid>56b6c430-cdca-4809-9f40-3053a2f55b0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newPassword']</value>
      <webElementGuid>057a54c5-036c-4dbe-8b22-1524043272e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>9a114f85-df6b-4d6f-b119-df27a900122c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'newPassword' and @type = 'password' and @placeholder = 'New Password']</value>
      <webElementGuid>9c013a7d-7505-45ad-8c31-540ea56cc978</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
