<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_test</name>
   <tag></tag>
   <elementGuidId>e518208f-cb20-4f0d-852e-aac063b04e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description2d729599-3453-48a7-b93f-845cf7b75dfd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='description2d729599-3453-48a7-b93f-845cf7b75dfd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;test&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b6ead20-cc1e-48f3-9b9a-8046095320bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>66c0a98f-572a-4231-9743-e83c2793c0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-collapse collapse show</value>
      <webElementGuid>ed8f393e-83c0-4db7-903a-dcc551f19fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description2d729599-3453-48a7-b93f-845cf7b75dfd</value>
      <webElementGuid>3134a607-b998-419b-8388-125db3431408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>4d3a754f-8926-409b-aa87-3161890a6a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flush-collapse147c8bcd-d145-4612-b95b-27182de9eaa0&quot;)/div[@class=&quot;ec-row d-flex flex-row card-course py-2&quot;]/div[@class=&quot;col-6&quot;]/div[@class=&quot;d-flex flex-row gap-2 checkbox-container&quot;]/div[@class=&quot;d-flex flex-column&quot;]/span[@id=&quot;description2d729599-3453-48a7-b93f-845cf7b75dfd&quot;]</value>
      <webElementGuid>9a609190-7278-443d-b133-4da05e980ade</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='description2d729599-3453-48a7-b93f-845cf7b75dfd']</value>
      <webElementGuid>bb90e3da-2f47-48ca-9a27-ba7b8cc19ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flush-collapse147c8bcd-d145-4612-b95b-27182de9eaa0']/div[5]/div/div/div/span[2]</value>
      <webElementGuid>b7913a16-d751-4f88-b154-b252a725f054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Golang Database'])[1]/following::span[1]</value>
      <webElementGuid>9eb48d4e-ab3a-44eb-9504-d5bf3f8aa75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check / uncheck module according your need'])[1]/following::span[2]</value>
      <webElementGuid>141380ed-95c9-464c-ba38-553b904577b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp200,000'])[1]/preceding::span[1]</value>
      <webElementGuid>8119067b-7b76-4120-8ae4-baf1a025a4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp120,000'])[2]/preceding::span[2]</value>
      <webElementGuid>1f932ee8-60f4-47b8-afc9-c06d1b572294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>da401be8-9ac3-458a-98ab-d960a256810f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>9cd29593-48e7-4240-ae15-3f391493e88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'description2d729599-3453-48a7-b93f-845cf7b75dfd' and (text() = 'test' or . = 'test')]</value>
      <webElementGuid>87b9d0ac-ed47-4637-83f9-8970eed71fb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
