<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Course</name>
   <tag></tag>
   <elementGuidId>584704a3-e837-4da0-bb8c-6c2abcfeb580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.subtitle-20.fw-bold.ec-primary-500</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flush-collapse147c8bcd-d145-4612-b95b-27182de9eaa0']/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Course&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d96af931-142e-4d5e-9261-bda85831b5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subtitle-20 fw-bold ec-primary-500</value>
      <webElementGuid>bca0272a-b411-428f-92f8-95b92ea59d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Course</value>
      <webElementGuid>a9f13d62-9813-4cd5-895d-3ce95fea4198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flush-collapse147c8bcd-d145-4612-b95b-27182de9eaa0&quot;)/div[@class=&quot;ec-row pt-2&quot;]/div[@class=&quot;col-12&quot;]/span[@class=&quot;subtitle-20 fw-bold ec-primary-500&quot;]</value>
      <webElementGuid>240339f9-e6b9-41c9-bff3-9d639641f6d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flush-collapse147c8bcd-d145-4612-b95b-27182de9eaa0']/div/div/span</value>
      <webElementGuid>4348d4b8-9b6b-48ce-a4b4-a0a5fb468c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize package'])[1]/following::span[1]</value>
      <webElementGuid>4a699e80-f2c7-427e-9b70-df64d035f9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='package fore'])[1]/following::span[2]</value>
      <webElementGuid>85c2ef15-ff45-4095-9b4c-552457e08eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check / uncheck module according your need'])[1]/preceding::span[1]</value>
      <webElementGuid>84dd6ceb-239f-4e37-a8b4-4ba8e6e7f82e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Golang Database'])[1]/preceding::span[2]</value>
      <webElementGuid>e84dc0ec-4ada-4052-8e62-f8bf13baeed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Course']/parent::*</value>
      <webElementGuid>4bc0e2c8-b26b-42b8-91ad-3694fde6942c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span</value>
      <webElementGuid>c63289c6-83b4-4b7e-92e2-3645324a4c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Course' or . = 'Course')]</value>
      <webElementGuid>d4eefaa7-71ac-49f0-a126-4fee6b55e1c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
