<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MALE</name>
   <tag></tag>
   <elementGuidId>22f07aae-f35d-4820-bfde-88545098fe33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a0bfe095ad13-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a0bfe095ad13-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;MALE&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>478595ad-4cd7-45ea-924c-43ef68637aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>32295aa1-6f99-4482-bfbd-f4e6fa758f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>588e75d7-fdfe-4e62-ad98-8552f3c16f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5b479cb-2803-43d2-a49b-cde505f2325d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a0bfe095ad13-1</value>
      <webElementGuid>1a67a306-9c5a-4957-b61f-2d467b3414fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MALE</value>
      <webElementGuid>aeddf5d2-38ea-4a06-a583-d62595545b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a0bfe095ad13-1&quot;)</value>
      <webElementGuid>ba92abfc-c478-439b-9286-4905f5042306</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a0bfe095ad13-1']</value>
      <webElementGuid>b04fd5d8-348a-462e-b4a2-96a17e402aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a0bfe095ad13']/div/div[2]/div[2]</value>
      <webElementGuid>a8bba019-44b4-4314-a220-745eeb7b6959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FEMALE'])[2]/following::div[1]</value>
      <webElementGuid>4f78a02f-9d77-4b46-beba-d2b5137ac47a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>945adf79-3e4a-4c14-ac07-794f009e63f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a0bfe095ad13-1' and (text() = 'MALE' or . = 'MALE')]</value>
      <webElementGuid>cf6efd19-8f8f-4f10-85b4-c08c49a7614d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aa27f7a1f8b0-1']</value>
      <webElementGuid>945ad30b-acf0-45b9-8d4b-abcc5016d99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='aa27f7a1f8b0']/div/div[2]/div[2]</value>
      <webElementGuid>56e0f183-ba46-4884-81fa-5d62034a7f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FEMALE'])[1]/following::div[1]</value>
      <webElementGuid>6227cd9b-e86f-4079-b35b-3a21d3d901e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aa27f7a1f8b0-1' and (text() = 'MALE' or . = 'MALE')]</value>
      <webElementGuid>4e35b1d3-38e5-4efb-aaf5-f61d2c4bf537</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
