<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FEMALE</name>
   <tag></tag>
   <elementGuidId>d2ca8b62-2402-4b5c-a4ea-341fb5e69ebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a0bfe095ad13-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a0bfe095ad13-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;FEMALE&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0807526b-e008-43db-b802-42c70c08e83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-marked</value>
      <webElementGuid>742a4304-ca46-4487-962e-6f7a07cb1aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>395047a8-160d-41d6-bccb-320f89f79cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17c4d495-7801-4365-a648-fa0683687554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a0bfe095ad13-0</value>
      <webElementGuid>1c4ed4a7-94cd-474d-bcb7-825865bce4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FEMALE</value>
      <webElementGuid>69970c90-6650-409f-aac4-36bb9eedbc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a0bfe095ad13-0&quot;)</value>
      <webElementGuid>402477d6-852b-4dba-ab43-e3dac992c829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='a0bfe095ad13-0']</value>
      <webElementGuid>42e09e7d-ed11-40eb-8222-4a409275c917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a0bfe095ad13']/div/div[2]/div</value>
      <webElementGuid>0b925887-1ac6-4a2f-96d1-100db04cd869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[2]/following::div[4]</value>
      <webElementGuid>91deddf4-05aa-4607-aa61-9499531fc07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MALE'])[1]/preceding::div[1]</value>
      <webElementGuid>d272f7f8-c8a7-4807-abb8-ea9d3e9c7002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div</value>
      <webElementGuid>64519c4f-305e-4dbb-ab2a-536a650fe3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'a0bfe095ad13-0' and (text() = 'FEMALE' or . = 'FEMALE')]</value>
      <webElementGuid>add33065-b098-4a12-a18f-58b947a97d1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
