<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Log In_ec-col-12 ec-col-md-8 d-flex jus_a23ce5</name>
   <tag></tag>
   <elementGuidId>2398bc95-7b4d-4f3c-b713-5f552790bde7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ec-col-12.ec-col-md-8.d-flex.justify-content-start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='home-banner']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ec-col-12 >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9ae9b3c-c291-4319-ab57-3581f9c543d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-col-12 ec-col-md-8 d-flex justify-content-start</value>
      <webElementGuid>7841e981-5512-4216-945d-abc5f03539b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-banner&quot;)/div[@class=&quot;ec-row&quot;]/div[@class=&quot;ec-col-12 ec-col-md-8 d-flex justify-content-start&quot;]</value>
      <webElementGuid>cd5a99fd-2a32-422a-a6dc-a879a14ccb29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='home-banner']/div/div</value>
      <webElementGuid>d3668c34-53d8-46e6-9508-2f9245082ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/preceding::div[2]</value>
      <webElementGuid>fc560c0a-a5f0-47b8-9d23-7d554945e6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>042bf60c-45db-482b-9c4a-67931f69e229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
