<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_4ProfileSecurityProfile Back General In_679758</name>
   <tag></tag>
   <elementGuidId>f5528d18-999d-4180-8a4c-098c0029ebef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.main-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=&quot;4ProfileSecurityProfile Back General Info Security PasswordYou are allowed to ch&quot;i >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d1fd5c8-6017-4e2f-ade1-e032e7525282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-content</value>
      <webElementGuid>bcdee9b3-3f24-4552-ae81-6691c3d2257e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 4ProfileSecurityProfile Back General Info  Security PasswordYou are allowed to change your passwordCurrent PasswordNew PasswordConfirmation New Password Save Password </value>
      <webElementGuid>13c317e4-a868-4dd8-b06c-23a83d3c7f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-pages[1]/div[@class=&quot;wrapper-container&quot;]/div[@class=&quot;main-content&quot;]</value>
      <webElementGuid>fba119c1-591b-4398-a430-ffe3023fc438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::div[1]</value>
      <webElementGuid>480b93c1-fce7-4e09-a9a1-bb6d8abf0243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[2]</value>
      <webElementGuid>088ea0a8-e355-4c48-9d40-a06577b884ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>10cd7e97-c741-41d2-8a02-64e9a840003e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 4ProfileSecurityProfile Back General Info  Security PasswordYou are allowed to change your passwordCurrent PasswordNew PasswordConfirmation New Password Save Password ' or . = ' 4ProfileSecurityProfile Back General Info  Security PasswordYou are allowed to change your passwordCurrent PasswordNew PasswordConfirmation New Password Save Password ')]</value>
      <webElementGuid>f4d85e53-4725-42a7-95cc-a6c4426c5f28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
